version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=sokny
      - POSTGRES_PASSWORD=qwerty@123
      - POSTGRES_DB=db_postgres
    ports:
      - "6222:50"
    volumes:
  nginx:
    image: nginx:latest
    ports:
      - "90:92"
    volumes:
