version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "8080:80"
    volumes:
  nginx:
    image: nginx:latest
    ports:
      - "9090:90"
    volumes:
